name: p-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.2.4
  # - pdf2image=1.16.2
  # - poppler=22.12.0
  - pypdf==4.2.0
  - pip:
    - inference-schema[numpy-support]==1.3.0
    - xlrd==2.0.1
    - mlflow== 1.26.1
    - azureml-mlflow==1.42.0
      #- azure-ai-formrecognizer==3.2.0
      #   - azure-ai-ml==1.2.0
      #   - python-dotenv==0.21.0
